name: task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.3.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
     - assets/images/